### ISSUE TITLE
Decoder Source Code

### ISSUE THREAD

**Issue by phiresky** [facebookresearch/LASER#14]
It seems that the multilingual decoder mentioned in the [blog post](https://code.fb.com/ai-research/laser-multilingual-sentence-embeddings/) is not currently in this repository. Do you have plans to open source it?

**Comment by hoschwenk** [comment]
Hello,
Thanks for your interest in this work.
We provide a multilingual ENCODER for 93 languages. It can be used to get sentence representations for any of the supported languages (and it generalizes well to similar ones).
We provide an already trained  system, you don't need the decoder. We will also open-source the training code, but training a system on 93 languages need some resources (2 days on 16 GPUs).
Normally, there is no need to train your own model since the sentence embeddings can be used directly without any fine-tuning.

**Comment by loretoparisi** [comment]
@hoschwenk it makes sense. By the way is out there a reference paper/architecture?

**Comment by hoschwenk** [comment]
Yes, please have a look a at reference [6] in the README

**Comment by phiresky** [comment]
Sorry for the confusion - I was asking for the code and a pretrained model for decoding the embedded representation back into a sentence as described here:

> These sentence embeddings are used to initialize the decoder LSTM through a linear transformation, and are also concatenated to its input embeddings at every time step. There is no other connection between the encoder and the decoder, as we want all relevant information of the input sequence to be captured by the sentence embedding.
> The decoder must be told which language to generate. It takes a language identity embedding which is concatenated to the input and sentence embeddings at every time step.

Since as it is, the model can only be used for classification or retrieval based tasks (e.g. similarity), but not for text generation tasks. [Skip-Thoughts](https://github.com/ryankiros/skip-thoughts/tree/master/decoding) is an example of an existing model that can decode the embedding back to an english sentence.

(Unless I'm missing something)

**Comment by hoschwenk** [comment]
Your are right, in principle, you can use the decoder to create an English or Spanish sentence, for an input in any of the supported languages.
However, we do not expect to be better than other NMT systems since we use a fixed-size sentence representation for classification and retrieval tasks, instead of attention.
