### ISSUE TITLE
[QUESTION] LASER and fastText

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/LASER#15]
I'm using fastText for both unsupervised language model and as supervised text classifier. Currently for cross-language models fastText has several limitations, due to the approach in sub-words creations, that is limited in terms of text tokenization and it does not handle properly languages without word boundary etc. I was wondering how to combine LASER multilingual text embedding with a fastText model: fastText supports pre-trained vectors, so would it be possible to load the LASER bi-LSTM embeddings for training? Or maybe a different approach could be followed.
_Cross-side note._ In [this](https://arxiv.org/abs/1901.04831) recent paper we have exploited a fastText+biLSTM+Attention model and we have found pretty interesting results (mono-lingual), and I would like to extend these results including LASER at some point!

**Comment by hoschwenk** [comment]
Using fastText to initialize the embeddings is indeed a promising idea and we have actually tried this. However, it is a little bit tricky since we are using joint BPE over many languages.
LASER calculates directly embeddings for the entire sentence - this usually works better than combining word embeddings (e.g. bag of words) for tasks which are more at the semantic than syntax level.
I'll have a look at your paper !
