### ISSUE TITLE
Tokenizer does not recognise sr (Serbian)

### ISSUE THREAD

**Issue by Aidenloe** [facebookresearch/LASER#173]
What is the shorthand for the Serbian language that the tokeniser understand? I've tried sr, rs, srp, serp, serbian, Serbian and SERBIAN. None works. 

- Encoder: loading /xxx/xxx/projects/laser/models/bilstm.93langs.2018-12-26.pt
 - Tokenizer:  in language sr  
WARNING: No known abbreviations for language 'sr', attempting fall-back to English version...

**Comment by hoschwenk** [comment]
"sr" is correct, but we use the Moses tokenizer which has no special rules for Serbian, and therefeore, falls back to English (as for many other languages). That's the expected behaviour.

We will shortly publish the LASER2 model which has better performance and uses sentence piece, i.e. no issues with tokenization any more.
