### ISSUE TITLE
LASER2 vocab contains upper case characters

### ISSUE THREAD

**Issue by ZJaume** [facebookresearch/LASER#220]
Despite the mandatory preprocess of lowercasing everything, I found many tokens that contain uppercase characters.

```
$ grep -c '[A-Z]' laser2.cvocab
2741
```

which means that 2741 token spots of the vocabulary (and probably also in the input embedding layer) are being wasted?

**Comment by avidale** [comment]
They are not wasted, because word case often affects the semantics. 
Here are some illustrative examples collected by community: https://www.quora.com/What-words-change-their-meaning-when-they-are-uppercase-or-lowercase.

**Comment by ZJaume** [comment]
Yeah, of course casing affects the semantics. But it is explicitly stated in the code that lowercase is needed for all the models and it is also applied before tokenizing with SentencePiece.
https://github.com/facebookresearch/LASER/blob/faf08e8f12b4bda949b75c057b9a70e07c099fbc/source/lib/text_processing.py#L140
Therefore, neither SentencePiece or the model see any of those upper case characters.

**Comment by heffernankevin** [comment]
Hi @ZJaume, thanks for pointing this out! Indeed when I just checked myself I see upper-case characters in the trained vocabulary. It's possible a small amount of upper-cased data ended up in the sample used to train the sentencepiece model. However I would recommend continuing to use lower-cased inputs for inference since the training data was not cased.
