### ISSUE TITLE
get sentence embeddings in python

### ISSUE THREAD

**Issue by alejandrojcastaneira** [facebookresearch/LASER#32]
First of all, definitely a great framework, I would like to congratulate you and thank you also for sharing it, the idea of multilingual embeddings really is great. 

My doubt is, I was able to run the sample to obtain the embeddings for sentences in CLI, is there a way to get these embeddings in Python without the need to enter the sentences from one file and read the result as a numpy array, from another. 

That is to call some function like: 

encoder.embed ("sentence") or something similar.

Thank you, kind regards
Alejandro.

**Comment by BeWe11** [comment]
```python
import itertools
import os
import sys
assert os.environ.get('LASER'), 'Please set the enviornment variable LASER'
LASER = os.environ['LASER']
sys.path.append(LASER + '/source')
from embed import SentenceEncoder

MODEL_DIR = f"{LASER}/models"
ENCODER_PATH = f"{MODEL_DIR}/bilstm.93langs.2018-12-26.pt"


encoder = SentenceEncoder(
        ENCODER_PATH,
        max_sentences=None,
        max_tokens=12000,
        sort_kind='mergesort',
        cpu=True)

sentences = [
    'This is a sentence.',
    'This is another sentence.',
]

embeddings = encoder.encode_sentences(sentences)
```

**Comment by alejandrojcastaneira** [comment]
Not so sure if this the correct aproach, acording to the reference paper: https://arxiv.org/abs/1812.10464 the sentence must be transformed in to a BPE vocabulary.
First it should be applied the tokenization which it's language specific, btw/ spacy tokenization works well, and you can use it for a lot of the pretrained languages.
After this point, it should be applied the BPE transformation, the output of this step, I believe that It should be the input of the method encoder.encode_sentences.
Thanks for sharing and replying, please correct me, if I misunderstood something.

**Comment by BeWe11** [comment]
I think you may be right, it was just a quick test that I did and I got reasonable results (as in: embeddings that should be similar were similar).

Looking at `LASER/embed.py`, all the steps that you mentioned are being performed, but only if the corresponding command line arguments are given. It seems to be intentional that the `SentenceEncoder` can be used with simple strings. Maybe someone else can comment on this.

**Comment by hoschwenk** [comment]
Hello,
if you only want to embed an already preprocessed sentence, then you can do this entirely in Python (see emped.py).
Currently , we use external tools to perform preprocessing (e.g .Moses tokenizer an text normalization, Jieba for Zh, Mecab for Ja, and fastBPE). many of these tools are not in Python and that's why we use files to interact with them.
But you can do this for a single line of text (using temporary files). Normally, this is implemented in TokenLine etc (lib/text_processing.py)
