### ISSUE TITLE
About Greek romanization

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/LASER#56]
In the `Token` I see that the `transliteration` package is used 

```
# Romanization (Greek only)
ROMAN_LC = 'python3.6 ' + os.path.join(CURRENT_PATH,'romanize_lc.py') + ' -l '
```

and piped to the output like:

```python
tok = check_output(
            REM_NON_PRINT_CHAR
            + '|' + NORM_PUNC + lang
            + '|' + DESCAPE
            + '|' + MOSES_TOKENIZER + lang
            + ('| python3.6 -m jieba -d ' if lang == 'zh' else '')
            + ('|' + MECAB + '/bin/mecab -O wakati -b 50000 ' if lang == 'ja' else '')
            + '|' + ROMAN_LC + roman,
            input=line,
            encoding='UTF-8',
            shell=True)
```

While for `zh` and `ja` it is optional. Could it be improved checking the input language to be romanized here as well? Also the `transliteration` handles not only Greek but Russian/Armenian and other languages, so it will be applied in this case as well.

**Comment by hoschwenk** [comment]
Romanization is only used for Greek since no other language uses that script. By these means, there's no need to reserve BPE tokens for Greek letters.
All the other languages MUST not be romanized even if the romanization tool can handle them.
The encoder was trained with the native scripts.

You should set "romanize=True" when calling TokenLine() for Greek texts.
This could be indeed automatic, but we preferred to keep it flexible.

**Comment by loretoparisi** [comment]
@hoschwenk thanks, so it could be used like

```python
...
 + ('|' + MECAB + '/bin/mecab -O wakati -b 50000 ' if lang == 'ja' else '')
            + ('|' + ROMAN_LC + roman if romanize else ''),
            input=line,
```

**Comment by hoschwenk** [comment]
@loretoparisi 
The pipe is still needed since ROMAN_LC (i.e. romanize_lc.py) performs lower casing for all languages.
