### ISSUE TITLE
What is the best way to compare short sentences (1-4 words) in different languages?

### ISSUE THREAD

**Issue by vadal** [facebookresearch/LASER#58]
I use LASER to achieve this with the combination of cosine similarity and it works fine for near or exact translations, but I get medium percentages (40-50%) between irrelevant translations. 
I use SentenceEncoder, TokenLine to tokenize each sentence, BPEfastApplyLine, I am calculating embeddings and then cosine similarity.

**Comment by hoschwenk** [comment]
What is the final goal of your approach ?
When two sentences are not semantically similar (in the same or different language) then it is expected that the distance is large.
Therefore it is totally normal that the cosine is 0.4-0.5 between "irrelevant translations"

**Comment by vadal** [comment]
Thank you for your reply!
For example, the cosine similarity between "Software Engineer" and "Μηχανικός Λογισμικού" is 0.9+ (the second one is the exact translation in greek) but the cosine similarity between "Software Engineer" and "Δάσκαλος" is 0.58 (Δάσκαλος means teacher in english).

My final goal is to see how similar are two terms or sentences in the same or different language.

**Comment by loretoparisi** [comment]
An interesting case when comparing sentences with very few words (2-3 with the article) is the following

`the great pretender` (en)   -> `il grande pretendente (it)` = `0.9`

while

`the great pretender` (en)   -> `il grande perdente` (it) = `0.72`

where the term `perdente` in it is `loser` in en.

In this case it seems that the model has learned too few for this specific pairs `(pretender,perdente)`.

Another example, that puzzles me is to check the weight of the words in the embeddings, like in the the following:

`the great pretender` (en) -> `il grande` (it) = `0.73`.

**Comment by loretoparisi** [comment]
Here it is another interesting use case for short sentences:

`Y que se mueran to a las envidiosa` (es) -> `And let the envious die` (en) = `0.49`
`Y que se mueran to a las envidiosa` (es) -> `And let the jealous die` (en) = `0.71`

where the terms `jealous` and `envious` are synonymous, but it is possibile that the model has not learned too much info about the latter term, that it could be due to the fact that term it is not a common spoken language term  - I guess.

**Comment by bittlingmayer** [comment]
@loretoparisi Your numbers are similarity (not distance), right?

`to` is not not really Spanish, and `envidiosa` is not declined correctly.  Would be good to do the test with valid input.

That said, IMHO these types of models are as less for comparing a candidate against an absolute threshold, and more for comparing multiple candidates against each other.

(Because although we all know what 1.0 means here, nobody really has any idea what 0.9, 0.5 or even 0.0 means in the abstract.)

And it's an easier way to debug - find a group of pairs for which a worse candidate gets a better score than a significantly better candidate.

**Comment by hoschwenk** [comment]
Hello,
LASER is mainly trained on full sentences as you find them in the usual parallel resources. I believe that the average length is at least 10 words. Nevertheless, it seems to work quite well on shorter sentences, but I don't expect it to work well for individual words. It is an statistical approach. One will probably find some counter examples with unexpected behaviour. What are your error rates on a larger test set ?

Also, as pointed out by @bittlingmayer  , it is tricky to rely on absolute values of the cosine similarity.
You may want to experiment with a margin criterion. This is implemented in the code for bitext mining and filtering, and already used in multilingual WORD embeddings (see MUSE on github and references therein).
