### ISSUE TITLE
Using Laser purely in Python

### ISSUE THREAD

**Issue by PawelFaron** [facebookresearch/LASER#73]
Currently Laser has dependency to FastBPE which has to be compiled from C to be usable. It makes it hard to use it in serverless manner. Do you know maybe some way to overcome this? I would like to use it in AWS environment.

**Comment by yannvgn** [comment]
Hey, I've created a package that should match what you're looking for.
https://github.com/yannvgn/laserembeddings

It's possible to use it in a serverless environment (it should be quite straightforward if you're familiar with deploying ML projects to AWS lambda). Ah and have a look at the README, there's a note on how to pull the models from s3.

**Comment by hoschwenk** [comment]
@yannvgn , thanks a lot for creating the pip package for LASER !
As you wrote, there are (minor) difference in tokenization and BPE processing since the corresponding Python packages do not produce the exactly same results.
I was aware of this for fastbe against subword-nmt, but the Python version of Moses should produce the same results. The difference which you observe could be explained ny the fact that LASER uses the the release 4 of Moses (a slight change was introduced in the Moses tokenizer after training the models)
